### ISSUE TITLE
colorado dept of corrections denver-mushed text

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/gi-bill-comparison-tool#186]
https://staging.vets.gov/gi-bill-comparison-tool/institutions/search?military_status=national%20guard%20/%20reserves&spouse_active_duty=no&gi_bill_chapter=31&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=yes&number_of_dependents=3&online_classes=both&institution_search=dc&source=search&page=11&num_results=9&employers=true&page=1&num_results=9

![screen shot 2015-11-10 at 10 51 54 pm](https://cloud.githubusercontent.com/assets/13770771/11083443/bf52b45e-87fd-11e5-850b-41e7e60f118d.png)

**Comment by saintsoup52** [comment]
This is an issue for only a few schools... could we just reduce the font size if the school name is over so many characters?
