### ISSUE TITLE
Video links to something that does not exist Wk 2 (Rick 2)

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/gi-bill-comparison-tool#227]
![screen shot 2016-01-28 at 1 27 03 pm](https://cloud.githubusercontent.com/assets/1307774/12659294/ee20a342-c5c2-11e5-8fc8-3c7e8680924f.png)

**Comment by saintsoup52** [comment]
Took me awhile to find it... not sure why it was moved...

But it is called the "Know Before You Go" and it can be found here:
https://www.youtube.com/watch?v=Z1ttkv9oRI4
