### ISSUE TITLE
VA Common 3.5 produces incorrect links in footer.

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gi-bill-comparison-tool#237]
Links on the footer do not resolve correctly. For example, on my local machine, the browser link to 
"Help us create a better vets.gov ..." in the footer yields the href:

"http://localhost:3000/%7B%7B%20site.url%20%7D%7D/2015/11/11/why-we-are-designing-in-beta.html"

This was the same behavior found on staging.vets.gov before rollback

"http://staging.vets.gov/%7B%7B%20site.url%20%7D%7D/2015/11/11/why-we-are-designing-in-beta.html"

**Comment by mphprogrammer** [comment]
![screen shot 2016-02-02 at 3 13 35 pm](https://cloud.githubusercontent.com/assets/4104431/12763069/779b91e4-c9c0-11e5-9f44-414e6b101dc9.png)

There are also issues with rendering

**Comment by emilyville** [comment]
Are you sure it's not old cached CSS? If not, please file this issue on
va_common repo since that's where the problem lives.

**Comment by mphprogrammer** [comment]
Not sure where the problem lies yet, we need to look at how the css/js code is set up on the GIBCT. The problem may also be with the tool and not the gem. There were some problems in following the set up of the gem because of the way things are set up here: @imports used in application.scss rather than application.css

/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any styles
 * defined in the other CSS/SCSS files in this directory. It is generally better to create a new
 * file per style scope.
*/

@import 'jquery-ui';
@import 'va_common_main';
@import '_scss/all.scss';
