### ISSUE TITLE
EDU would like Utility Links Replaced

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#249]
Trace: @saintsoup52

**Comment by rickleegit** [comment]
<img width="1543" alt="screen shot 2016-02-08 at 4 00 43 pm" src="https://cloud.githubusercontent.com/assets/11138830/12899412/3ae8bbbe-ce7f-11e5-9d3c-b82cae7c754e.png">
<img width="1543" alt="screen shot 2016-02-08 at 4 00 54 pm" src="https://cloud.githubusercontent.com/assets/11138830/12899413/3aec8532-ce7f-11e5-805e-e5e8da97ba4c.png">
<img width="1543" alt="screen shot 2016-02-08 at 4 01 01 pm" src="https://cloud.githubusercontent.com/assets/11138830/12899414/3af1f40e-ce7f-11e5-9e6b-a43a0254aff2.png">

**Comment by rickleegit** [comment]
https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/pull/251

**Comment by rickleegit** [comment]
Optimized these in https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/pull/264

- [x] Removed "accessibility" - redundant with vets.gov accessibility statement
- [x] Changed "feedback" to "report data inaccuracies" to provide clarity of purpose and to distinguish from UserVoice channel.

<img width="613" alt="screen shot 2016-02-11 at 6 16 18 am" src="https://cloud.githubusercontent.com/assets/11138830/12975735/178248e8-d08c-11e5-887e-d7e736c47c4c.png">

**Comment by saintsoup52** [comment]
I know EDU will have feelings about this... but most of the reports we received from some schools that are supposedly wrong with the tool are actually not inaccurate. 

I don't think it is wise to frame the question so negatively because this will encourage even more feedback like that.

**Comment by rickleegit** [comment]
It is critical for vets.gov to distinguish this feature from our general feedback mechanism, User Voice. After the call yesterday, where it was reported that 95% of all feedback was related to data inaccuracies, this seems like the most accurate and explicit language.

**Comment by SteffieP** [comment]
Since this was not presented to us prior to putting it on the site we want it taken down. The verbiage is definitely a problem

**Comment by rickleegit** [comment]
For today's deployment, I will simply remove the link all together. We will
need to work on, and settle on language that is acceptable.
