### ISSUE TITLE
Increase test coverage >= 90%

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/gi-bill-comparison-tool#254]
The goal of this task to ensure that at least 90% of the lines of code are covered by test coverage.

Accomplishing this involves:
- [ ] Use SimpleCov to measure coverage (Road Runner provides an example)
- [ ] Increase unit test coverage (Rpsec)
- [ ] Increase integration test coverage (Rspec, Capybara)
- [ ] Enable Travis CI builds
- [ ] Enable protected branches (PR merges cannot be completed unless coverage is achieved)

**Comment by saintsoup52** [comment]
This is exciting... what are we testing?

**Comment by mphprogrammer** [comment]
Rpsec/Capybara tests on the code to make sure (1) its doing what we think it should be doing, and (2) ensuring that code changes don't break any existing functionality. Tests will run automatically, and unless a certain "amount" of code is referenced in the test, we will not be able to merge our changes with the master.

**Comment by rickleegit** [comment]
@saintsoup52 This is a bunch of tech testing. 508 compliance and others!

**Comment by mphprogrammer** [comment]
Closing this, no longer relevant.

**Comment by rickleegit** [comment]
I thought you always had >90% test coverage, Mark?

**Comment by mphprogrammer** [comment]
For the Data Service it is 100%, but for the GIBCT I was told to only provide basic tests (the 5 week deadline loomed large)

**Comment by rickleegit** [comment]
Was jk. Clearly not funny.

**Comment by mphprogrammer** [comment]
Sorry - I can be a bit dense ...
