### ISSUE TITLE
Add breadcrumbs to GI Tool Page

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/gi-bill-comparison-tool#255]
We need to add the breadcrumbs to the GI Tool page so that it fits appropriately into the rest of the architecture. 

It should be Education Benefits > GI Bill > GI Bill Comparison Tool

![screen shot 2016-02-09 at 6 43 39 pm](https://cloud.githubusercontent.com/assets/1307774/12934570/8fa3ed0c-cf5d-11e5-81a5-c081ac6effb2.png)

Here is the GI Bill page for comparison
![screen shot 2016-02-09 at 6 44 10 pm](https://cloud.githubusercontent.com/assets/1307774/12934571/91b6e0c2-cf5d-11e5-9019-d55babef731a.png)

**Comment by rickleegit** [comment]
https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/pull/256
