### ISSUE TITLE
Code review of master prior to deploy

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gi-bill-comparison-tool#263]
Needed to get the code on staging for stakeholder review, but would like a quick review prior to production push.

**Comment by plusjeff** [comment]
Is there a specific thing or things to review?

**Comment by mphprogrammer** [comment]
No, just a general check - any comments you may have in general ... I know there isn't much time left at this point.

**Comment by plusjeff** [comment]
Will take a quick peak, but broad code reviews aren't typically effective is much more effective.

https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/

**Comment by mphprogrammer** [comment]
Ah - in that case, search and pagination would be what to focus on

**Comment by plusjeff** [comment]
Will do

**Comment by plusjeff** [comment]
Any reason this can't always be request.host?
https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/blob/master/app/controllers/institutions_controller.rb#L3

**Comment by mphprogrammer** [comment]
It was a dev thing for me to check links. Without that if, the link would fail. I will comment it out, and use request.host only.

**Comment by mphprogrammer** [comment]
Come to think of it, I don't even use it at this point. I'll take care of it on my end.

**Comment by plusjeff** [comment]
There's currently a test failure:

```
  1) load_csv floats valid strings are floats
     Failure/Error: @floats.each { |float| puts "@@@@@@@@@@@@ #{float}"; expect(row[float]).to eq(valid_float_value) }
       
       expected: 1234.5
            got: nil
       
       (compared using ==)
     # ./spec/tasks/build_db_spec.rb:59:in `block (4 levels) in <top (required)>'
     # ./spec/tasks/build_db_spec.rb:59:in `each'
     # ./spec/tasks/build_db_spec.rb:59:in `block (3 levels) in <top (required)>'

Finished in 2.89 seconds (files took 1.83 seconds to load)
29 examples, 1 failure

Failed examples:

rspec ./spec/tasks/build_db_spec.rb:57 # load_csv floats valid strings are floats
```

**Comment by mphprogrammer** [comment]
That shouldn't even be in there. Wasn't mean for this deploy. dang - i'll make sure its out!

**Comment by plusjeff** [comment]
Other than that - nothing jumps out at me. The Kilter stuff helps reduce the amount of pagination logic in the controller methods quite a bit!

**Comment by plusjeff** [comment]
Feel free to assign me to the PRs for these. After that, will move onto #233

**Comment by mphprogrammer** [comment]
Yes, and ironically, that is a root of another problem - the one I am fixing now. Pagination won't pick up the changes on the top search form (online, military status, etc) if they change in the search form. When I finish tonight, I'll PR and assign you to review that!

**Comment by mphprogrammer** [comment]
Thanks Jeff!
