### ISSUE TITLE
Advance Search Alignment Issue

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#267]
![advance search alignment](https://cloud.githubusercontent.com/assets/15673554/12984643/a38dc68e-d0bc-11e5-9082-87c9e9e6f5cb.jpg)

On the attached screen shot... the sections outline in red are aligned incorrectly

**Comment by rickleegit** [comment]
This is a result of moving the filters back to the left rail. It occurs on several with long names. We will attack this for the next push.

**Comment by SteffieP** [comment]
Is it going to display like this to the end user?

**Comment by rickleegit** [comment]
Yes Until we can fix it. But I am looking into what that will take right
now.

**Comment by rickleegit** [comment]
resolved: #233
