### ISSUE TITLE
Blank spaces when using advanced search

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#268]
![blank spaces on advance search](https://cloud.githubusercontent.com/assets/15673554/12984984/647de81e-d0be-11e5-93db-04ba4d8250b1.jpg)

On the the attached screen shot......Page 2 of 12 The Advanced search is populating blank spots
 The red stars are spaces that should be populated

**Comment by rickleegit** [comment]
@mphprogrammer: Do you know why this is happening?

**Comment by mphprogrammer** [comment]
No idea... The only changes I made layout-wise were removing the old pagination code.

**Comment by mphprogrammer** [comment]
Rick - this isn't a rails issue, perhaps styling.

**Comment by rickleegit** [comment]
@ericks24: Can you give us more details on this? What was the query you entered? Did you apply any of the filters to achieve this result?

**Comment by ericks24** [comment]
Just type "Pennsylvaina" in search

**Comment by rickleegit** [comment]
We just executed that search, but we are not able to recreate the issue. Does this occur on subsequent pages as well as page 2?

**Comment by rickleegit** [comment]
@ericks24 Can you also provide your browser version information?

**Comment by ericks24** [comment]
So far i am seeing this issue just on page 2 when typing "Pennsylvania" in seach. I am using IE11

**Comment by rickleegit** [comment]
@ericks24 OK I think we have found the issue. Working on a fix right now. cc; steffiep

**Comment by rickleegit** [comment]
@ericks24 The changes are posted on staging. Can you take a look and verify that both this one and the alignment issue are fixed for you?

**Comment by rickleegit** [comment]
IE 11 screen cap. 

![bs_win8 1_ie_11 0](https://cloud.githubusercontent.com/assets/11138830/12990132/adf5dd4a-d0d6-11e5-9d67-226a2208c6f7.jpg)

**Comment by rickleegit** [comment]
resolved: #233
