### ISSUE TITLE
OJT Institution Pages

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#274]
@mphprogrammer On Institution pages for OJT opportunities, Your Estimated Benefits and Veteran Programs are not appearing.

Would expect to see Your Estimated Benefits as there are benefits represented in search results. 
Would expect to see Veterans Programs with all X'd entries. 

Maybe there is some conditional logic involved here? 

<img width="678" alt="screen shot 2016-02-12 at 8 03 18 am" src="https://cloud.githubusercontent.com/assets/11138830/13007577/4db33c3c-d15f-11e5-8f17-f79b3e0a1854.png">

**Comment by mphprogrammer** [comment]
Somehow the layout has changed, and its weird. No logic should have changed, and the layout appears wrong.

**Comment by mphprogrammer** [comment]
![screen shot 2016-02-12 at 9 39 26 am](https://cloud.githubusercontent.com/assets/4104431/13009828/99fbaa86-d16c-11e5-9380-740d3e8cbc74.png)

**Comment by mphprogrammer** [comment]
This looks like its been like this since the end of Dec.

**Comment by mphprogrammer** [comment]
Also, started moving profile components, e.g., estimator, location, etc into sub-views to clean up code and make html readable.

**Comment by mphprogrammer** [comment]
Jeff - could you check that the moving of partials solved the problem on your machine.
