### ISSUE TITLE
GI Tool SVA Demo Prep

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/gi-bill-comparison-tool#277]
SVA demo 2/24 prep; session currently not yet scheduled (?); need room reservation; outlook invite; dry run of materials w/ Scott Blackburn and Martin Taylor prior (overview is fine--30 min meeting to make sure we are on same page w/ Scott).

**Comment by koconnor719** [comment]
do you have a "PM" label? would this be helpful?

**Comment by rickleegit** [comment]
2/15 - Reached out again to Broader team to get this scheduled. Doug has not been responsive.

**Comment by rickleegit** [comment]
2/16 - Scott Blackburn advocating for 2/24 meeting. Need response from Doug to get this scheduled.

**Comment by koconnor719** [comment]
i'm assuming you are leading all coordination and prep on this, correct?  since it's SVA and GI tool?  if not, please let me know and i'll coordinate w/ scott.

**Comment by koconnor719** [comment]
Doug sits up on 8th floor; you might just walk up there when you are in office.  that�s how I usually get him.

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by rickleegit** [comment]
Call Scheduled for 2/16/1PM with Martin, Doug, Scott and Will.

**Comment by rickleegit** [comment]
Just got off a call with Martin, Doug and Will. Meeting notes below:

Meeting notes below:

Targeting March 10 Date – 3PM – 5PM  - Will to confirm with SVA Comms Team 
Webinar only (no physical attendance) will maximize participation.
Martin would like to review presentation materials (Rick will coordinate 1st draft with Martin no later than 2/29)
Invitations: Doug, Will, Rick to coordinate
Doug's team will craft invitations (Per Martin)
Doug/Will to coordinate recipient list/distribution (Will to consult SVA Comms)
Doug will schedule webinar tool
Webinar will be open to public (no code required to participate)
Webinar will be recorded and archived for wide distribution
Possible to add recording to vets.gov?
Expect 25 – 50 participants although could reach 1000+Doug will schedule webinar tool
Webinar will be open to public (no code required to participate)
Webinar will be recorded and archived for wide distribution

**Comment by koconnor719** [comment]
Thx pls. include mary ann brody.
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by rickleegit** [comment]
2/24 - Meeting with MaryAnn and Emily regarding call to action and feedback mechanism.

**Comment by rickleegit** [comment]
[GRAPHIC] {attached}

[HEADLINE] 
Vets.gov Needs You!

[BODY] 
Join the Vets.Gov team on March 10, 2016 at 3pm ET/12PM PT for a webinar featuring the GI Bill® Comparison Tool. Learn more about the tool, its features and future enhancements that will help you maximize your hard-earned GI Bill benefits! Participate in a two way dialog and give us your much needed feedback to help us make the tool work for you, the Student Veteran. 

[OUTSTANDING REQUIREMENTS]
Doug, Scott, Martin: How have we handle these in the past?
Webinar Landing Page?
Link to ^
Sign-up/RSVP mechanism?

**Comment by rickleegit** [comment]
3/1 Update: Sent Scott/Martin draft content. Scott replied that we are good to go. 

3/2 Dry Run Scheduled with Barrett to ensure we understand the capabilities of the tech.

**Comment by rickleegit** [comment]
Webinar completed. Recording at: https://www.youtube.com/watch?v=MzaOQ9mXkJU and  https://plus.google.com/u/0/events/c0j1varq0qqjk29vvgt62kscvhc
