### ISSUE TITLE
Content Inventory

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/gi-bill-comparison-tool#278]
Inventory all GI Bill tool relevant content pages for rewrite, migration, and (future) sunset on VA.gov.

**Comment by koconnor719** [comment]
would a "content" label be helpful?

**Comment by rickleegit** [comment]
@koconnor719: would a "content" label be helpful?

Yeah it would. Will add a label for content and one for PM tasks.

**Comment by rickleegit** [comment]
@mollyblake: Hope you had a great vacation! 

Can we please proceed with the content audit that we discussed for the 'About this Tool' section?

**Comment by koconnor719** [comment]
Do we need to inventory all of the GI tool content pages?  Or do you have that already.

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by rickleegit** [comment]
[GIBCT Content Audit_20160308.docx](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/files/169453/GIBCT.Content.Audit_20160308.docx)
