### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/gi-bill-comparison-tool#279]
Understand current state GI Bill tool "feedback" processes in order to align w/ vets.gov "feedback" feature and process.

**Comment by rickleegit** [comment]
Meeting scheduled with Kelsey for 2/17.

**Comment by rickleegit** [comment]
Meeting scheduled with Barrett for 2/23.

**Comment by rickleegit** [comment]
@koconnor719: I now have a decent handle on the various channels in which the tool in receiving inbound. This information has been captured in a simple spreadsheet format. Do you have a preference for how you want this information? Bullets on a one-pager?

**Comment by koconnor719** [comment]
However you think easiest to communicate to the team.  Thanks.
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by koconnor719** [comment]
@rickleegit is there a process map or doc on this in your product folder? can you post a link to where the doc you reference above is? thx

**Comment by rickleegit** [comment]
Attached is as far as I have progressed. All the info is in this but I need to codify this into a doc. Been working on Webinar prep and FL prototype. Will get on this a after the webinar. 
[GIBCT Feedback Channels.xlsx](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/files/163186/GIBCT.Feedback.Channels.xlsx)

**Comment by koconnor719** [comment]
given the 

<img width="583" alt="screen shot 2016-03-08 at 9 00 04 am" src="https://cloud.githubusercontent.com/assets/13770771/13604121/44335516-e50f-11e5-9295-e498c4ebffcd.png">

**Comment by rickleegit** [comment]
OK I can loop back around on the expanded scope.  I limited my effort to GI Tool related channels.

**Comment by koconnor719** [comment]
Im not suggesting expanded scope. If you don�t think this is needed just close.
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by rickleegit** [comment]
I do think its a good idea. I'll make it happen. No worries.

**Comment by plusjeff** [comment]
Confirmed with Marc that this is complete.

**Comment by koconnor719** [comment]
@rickleegit  what is status of this?

**Comment by koconnor719** [comment]
@rickleegit can this be closed? was it completed per your comments above--seems like last comment back in march?
