### ISSUE TITLE
Advance Search Results for Mobile vs Computer

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#297]
![mobile](https://cloud.githubusercontent.com/assets/15673554/13154262/27aad9c8-d646-11e5-90c1-06dfe78198e0.jpg)
![computer](https://cloud.githubusercontent.com/assets/15673554/13154277/3444ff42-d646-11e5-8d72-f1e3a1fb3c2c.JPG)
![mobile illinois](https://cloud.githubusercontent.com/assets/15673554/13154297/4f6717d8-d646-11e5-9bef-ac8fec3322fa.jpg)
![illinois computer](https://cloud.githubusercontent.com/assets/15673554/13154305/590f6dc6-d646-11e5-9837-17c300cde325.JPG)

I noticed using the advanced search feature typing in "Tennessee or Illinios"..... you get different search results on Mobile Device vs Computer
The search results for Mobile Devices are less than the results using Computer.

**Comment by mphprogrammer** [comment]
Works the same on both mac and nexus - 210 results. Were any filters engaged?

**Comment by ericks24** [comment]
Filters are Veteran, Post 9/11, 36 Months, and Not online

**Comment by mphprogrammer** [comment]
Still getting 210 results...

**Comment by ericks24** [comment]
Are you getting 210 results on both computer and mobile device

**Comment by mphprogrammer** [comment]
Yes

**Comment by ericks24** [comment]
I just tested this scenario again using mobile staging site vs computer and using live CT on mobile vs computer.... I am getting different search results

**Comment by mphprogrammer** [comment]
You've got me baffled, I am getting the same on both... I'll look in the code, but there is no separate mobile site, both mobile and pc's use the same code. I'll ask rick to take a peek as well - Thanks!!

**Comment by mphprogrammer** [comment]
Could you try a search that you've never done before, like nevada ? do you get 42?

**Comment by ericks24** [comment]
Nevada i get 42 results on both

**Comment by mphprogrammer** [comment]
Wow, weird!! I will check some more...

**Comment by ericks24** [comment]
if you enter "California"  Mobile device is 122 and Computer is 190.

**Comment by mphprogrammer** [comment]
I am getting 190 on both! Are you on vets.gov or staging.vets.gov ?

**Comment by mphprogrammer** [comment]
The mobile shows vets.gov, could you reenter https://staging.vets.gov/gi-bill-comparison-tool in the mobile browser?

**Comment by ericks24** [comment]
I am go back and forth between staging and production...getting same results. I can send you screen shots from mobile staging if you like

**Comment by mphprogrammer** [comment]
yes - try a new search, one that you haven't done before.

**Comment by ericks24** [comment]
I just searched Indiana on mobile staging site and got 116. This same seach on computer got 261.

**Comment by ericks24** [comment]
Looks like when you use the mobile device it autopopulates a space at the end. When i delete the space the results match on mobile and computer. So the issue is when using mobile device it autopopulates a space at the end.

**Comment by rickleegit** [comment]
Its totally the space. we can replicate that now. Will have this fixed for the next deployment.
