### ISSUE TITLE
Caution Flag Tool Tips on Mobile vs Computer

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#298]
![mobile caution flag](https://cloud.githubusercontent.com/assets/15673554/13156715/e2618284-d651-11e5-90a3-927dc12b891a.jpg)
![computer tool tip](https://cloud.githubusercontent.com/assets/15673554/13156720/eabad85e-d651-11e5-9c63-536162b8d4aa.JPG)

The Caution Flag links on Mobile Device Tool Tips are missing compared to Computer.

**Comment by rickleegit** [comment]
Thanks Eddie!
