### ISSUE TITLE
Update Caution Flag for DeVry University

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#304]
Update Caution Flags for DeVry to say the following:

Notice of Intent Issued by Department of Educaton (ED)

**Comment by rickleegit** [comment]
Eddie, Pretty sure that this will need to be done in the data, if I am understanding correctly. 

@saintsoup52?

**Comment by saintsoup52** [comment]
@ericks24 All I need is a new settlement file with the updated language. If you could modify that file and resend that would be great.

I will send you the latest version just so you have it in your inbox.

**Comment by ericks24** [comment]
I am going to update the settlement file now and it will be your way shortly

**Comment by rickleegit** [comment]
@saintsoup52 @ericks24 : What is the status of this update? Should we be working this into this week's deployment plan?

**Comment by saintsoup52** [comment]
I was going to wait till the WEAMS data comes... but that might not be till Thursday. So should i send the file over now?

**Comment by rickleegit** [comment]
Wednesday around noon would be the cutoff. If nothing will change by then, by all means send it over. 

Are there content changes that need to go along with this?

You can attach the data to this issue and then reassign to Marc, if its data only, or me if it is data and content. 

cc: @mphprogrammer

**Comment by saintsoup52** [comment]
I will send tomorrow... There will be a change to the tool tip text (to match the caution flag code).

@ericks24 Can we get the latest complaint file?

**Comment by ericks24** [comment]
Complaint file coming shortly.  Also I need a school link changed for Everett College - Chesapeake

**Comment by saintsoup52** [comment]
@ericks24 Is it a web url link for the school? Because if it is...we get that from Dept of ED, so they need to update it with them.

**Comment by saintsoup52** [comment]
Actually this is a crosswalk issue... Everest College was paired with Averett College...  I will make the change

**Comment by ericks24** [comment]
@saintsoup52  Thanks for updating link.......I did let school know this has to be updated with Dept of Ed

**Comment by rickleegit** [comment]
https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/pull/319
