### ISSUE TITLE
Graceful error page for misspelling school name

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gi-bill-comparison-tool#310]
If a user mistypes a school name in the search box and no entries with that school name are found... the user is directed to random error page without explaining to them that no schools were found with that name.

![image](https://cloud.githubusercontent.com/assets/4397508/13347598/d1292ed6-dc3c-11e5-8072-baccf56ee1cd.png)

![image](https://cloud.githubusercontent.com/assets/4397508/13347613/e375cde2-dc3c-11e5-8123-3d5d6e7ca546.png)

**Comment by emilyville** [comment]
@rickleegit I think the simple field validation style with an inline
message from uswds would work great here!

**Comment by rickleegit** [comment]
@emilyville Great idea!

@mphprogrammer: Can we discuss making this happen for the next deployment?

**Comment by mphprogrammer** [comment]
@rickleegit There is actually an message printed out on the no-results page, but its colored the same as the background for some reason, so its not visible.

**Comment by rickleegit** [comment]
Yeah. That is a tag placement issue. But I am curious what it would take to
apply an inline solution as emily suggested.

**Comment by rickleegit** [comment]
Fixed and reviewable here: https://gi-bill-comparison-tool-pr-328.herokuapp.com/

cc; @saintsoup52 @ericks24 @SteffieP

**Comment by saintsoup52** [comment]
Works for me...

**Comment by rickleegit** [comment]
Resolved by https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/345
