### ISSUE TITLE
Create "data.csv" export from Data Service

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#314]

**Comment by rickleegit** [comment]
Week One Sprint:

**Comment by plusjeff** [comment]
@mphprogrammer has this at 90% complete.

**Comment by plusjeff** [comment]
Per @mphprogrammer : Requires complete set of CSVs that can be ingested.

**Comment by plusjeff** [comment]
@rickleegit has reached out to Patrick to get these files.

**Comment by plusjeff** [comment]
(Issue can go back to @mphprogrammer after CSVs gotten from Patrick)

**Comment by plusjeff** [comment]
Got files from Patrick. @mphprogrammer will upload to GitHub

**Comment by plusjeff** [comment]
ETA for 4/21 - end of day

**Comment by mphprogrammer** [comment]
Completed on 4/21
