### ISSUE TITLE
ITT Tech Institute-Pittsburgh (249B0438)

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#326]
![itt tech pittsburgh](https://cloud.githubusercontent.com/assets/15673554/13471186/8283d7e6-e07d-11e5-8b39-6b28cfe2817d.JPG)

@saintsoup52 
We are receiving complaints from School Certifying Officials and ELRs about not being able to pull up this facility on Comparison Tool. The attached screen shot is what comes up when selecting ITT Tech Institute-Pittsburgh. The school is on data dahboard.

**Comment by mphprogrammer** [comment]
The latest xls data file has those schools listed as ITT Technical Institute ...

**Comment by mphprogrammer** [comment]
![screen shot 2016-03-02 at 2 14 29 pm](https://cloud.githubusercontent.com/assets/4104431/13472027/214ca44a-e081-11e5-8127-5f5a4af4fbce.png)

**Comment by saintsoup52** [comment]
ITT Tech was the old school name... remember we aligned the school names with Dept of ED:

https://www.vets.gov/gi-bill-comparison-tool/institutions/profile?military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&source=search&institution_search=ITT%20Technical%20Inst&state=pa&page=1&facility_code=249B0438

**Comment by ericks24** [comment]
@saintsoup52  Clicking on the link you provided takes me to the school page just fine. If you search for school by typing in full name....still get above message i captured at top.

**Comment by saintsoup52** [comment]
@ericks24 That is because you are typing "ITT **Tech** Institute-Pittsburgh" vs ""ITT **Technical** Institute-Pittsburgh"

You have to spell out "technical'

**Comment by ericks24** [comment]
@saintsoup52  I am spelling it out. I was spelling it out to begin with didn't realized i put Tech instead of Technical on title of this issue. On CT now and still getting message

**Comment by saintsoup52** [comment]
@ericks24 there is no space before the hyphen:

![image](https://cloud.githubusercontent.com/assets/4397508/13494963/aba3b02c-e115-11e5-89e8-0a8a7dbaaeec.png)

**Comment by ericks24** [comment]
All of that comes up just fine. When i click on school still get message. 3 other ppl getting the same message when they click on school

**Comment by saintsoup52** [comment]
@mphprogrammer 

I see what you are talking about now... I am getting the same error message...

Are we not purging the the school search list? Or are we not pulling the data correctly?

**Comment by mphprogrammer** [comment]
I think I see an issue with the css - tell me if the same problem happens with ITT TECHNICAL INSTITUTE-LEVITTOWN, ITT TECHNICAL INSTITUTE-PHILADELPHIA  and even ITHACA POLICE DEPARTMENT

**Comment by mphprogrammer** [comment]
Sorry it should say xls not css darned spell check.

**Comment by mphprogrammer** [comment]
Whenever I get the CT Data file in xls, I open it up in excel and save as a csv. What you see below is a sample of that result. If you take a peek at the Facility Codes (1st column of data) you'll see some that are left-aligned and some are right aligned. The ones that are left-aligned (Such as ITT Tech in Pittsburgh) will not work. There is something in the left aligned facility codes that carries over when its made into a csv.

![screen shot 2016-03-03 at 9 16 37 am](https://cloud.githubusercontent.com/assets/4104431/13496929/d12ff9f8-e120-11e5-86e5-cb4d343fafaa.png)

**Comment by mphprogrammer** [comment]
ITT Tech in Pittsburg (Levittown, Philadelphia, ...) work fine when you do a partial name match to bring up the search page - because that search does not use the facility code.

**Comment by mphprogrammer** [comment]
It seems that all the facility codes excel treats as pure numbers (1234567890) because they don't have any letters in them work fine, but the fac codes with letters do not work.

**Comment by mphprogrammer** [comment]
Got the problem - autocomplete is comparing codes in the wrong case when using facility codes. If they are numbers that won't be an issue. but if there is text in them it will not match.

**Comment by SteffieP** [comment]
Marc you are awesome! ☺

**Comment by mphprogrammer** [comment]
Fixed - should go up today.
