### ISSUE TITLE
Data Update - Update Data to Reflect POE Removal

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#334]
One of the schools in our data base is having their POE status revoked effective Monday. Patrick (@saintsoup52) is working on the data updates today. 

Please include in the thursday deployment.

**Comment by mphprogrammer** [comment]
No problem on my end.

**Comment by plusjeff** [comment]
Will include it for the Thursday deploy.

**Comment by plusjeff** [comment]
Deployed.
