### ISSUE TITLE
Know Before You Go Video overlapping scroll bar on search command

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#342]
![img_2201](https://cloud.githubusercontent.com/assets/15673554/13866415/7c776f4c-ec8b-11e5-96d3-d8951cc87955.jpg)
The section outlined in red shows the video on main CT page overlapping search bar. This make it hard for user to scroll with down without clicking on video.

**Comment by rickleegit** [comment]
This is fixed with PR https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/compare/0322FE?expand=1
