### ISSUE TITLE
Deployment 3/31 (data only)

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#346]
This file is the data file for the 3/31 push. @mphprogrammer if you can get the CT prepped and ready with this data file, @plusjeff would like to push it this afternoon. He is OoO tomorrow and it would be great to accommodate his time off so he doesn't need to push tomorrow. 
[Comparison Tool Data Full 20160330 1437.xlsx](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/files/196231/Comparison.Tool.Data.Full.20160330.1437.xlsx)

**Comment by rickleegit** [comment]
@plusjeff: All you!

**Comment by plusjeff** [comment]
Great - thanks for the quick movement! I'll deploy right now.

**Comment by plusjeff** [comment]
New data file added in #347

**Comment by rickleegit** [comment]
@saintsoup52, @SteffieP @ericks24,

New data file has been pushed. Our dev-ops guru and tech lead superhero @plusjeff  is out of the office tomorrow and he gracious agreed to push this a day early. Thanks also to Patrick for hustling the data our way quickly. 

Screen Caps of data verification:

<img width="1440" alt="screen shot 2016-03-30 at 3 45 22 pm" src="https://cloud.githubusercontent.com/assets/11138830/14155286/1f52085a-f68f-11e5-8831-711fb92e5b6b.png">
<img width="1440" alt="screen shot 2016-03-30 at 3 46 52 pm" src="https://cloud.githubusercontent.com/assets/11138830/14155287/1f6946f0-f68f-11e5-833b-d9ae4a573e33.png">
<img width="1440" alt="screen shot 2016-03-30 at 3 50 16 pm" src="https://cloud.githubusercontent.com/assets/11138830/14155288/1f71ce06-f68f-11e5-90f4-6dd11d5d14b0.png">
