### ISSUE TITLE
SEARCH RESULTS - Pagination

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#36]
Need a way to paginate the search results. A few considerations:
- FE Filtering effects result count and subsequently page count.
- Not opposed to a lazy load if it is both 508 compliant **and** responds to filter inputs (although in thinking that through, this will likely face the same challenges as any pagination solution)
- There is no way around some form of pagination. If necessary, we may need to trigger a page reload to accomplish it. As unfortunate as this would be, it might be a more acceptable LOE than trying to integrate with FE filtering. I looked at amazon and home depot as analogs. They both seem to be pinging the server following engagement with the filters - Amazon reloads, Home Depot appears to be working some Ajaxy pixie dust. 
- No pressure, but the filtering is a core part of the functionality, so if additional brain power is needed to pull this off in a usable manner, let's assemble it sooner than later. :-)

**Comment by westurner** [comment]
From https://veterans.uservoice.com/forums/330333-vets-gov/suggestions/17635243-fix-pagination-n-divmod-n-per-page

> BUG: GI Bill Comparison Tool: search result pagination is off.
>
> Search query: "Omaha"
> 
> First it shows 5 results pages for 67 results, 
> Then when I click on 5 (for things starting with University), 
> It shows 1, 2 and Next. 
> Next works, but the pagination is off.

> To clarify, this is w/ Android 6 Chrome 55

Should I create a new issue?

**Comment by ayaleloehr** [comment]
A separate issue would be great @westurner ! thanks!

**Comment by westurner** [comment]
@ayaleloehr I've created a new issue: https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/455
