### ISSUE TITLE
Data Deployment for 05/12

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#362]
@mphprogrammer, @plusjeff, @saintsoup52 

Data Attached to issue for deployment on 5/12/2016. 

Validation Criteria:

New WEAMS file

o   UNIVERSITY OF SOUTH CAROLINA UPSTATE (fc # 11801040)

§  suspended

§  should not appear on CT

 

o   ACT SAN ANTONIO (fc # 21037743)

§  Now approved

§  Should appear on CT

 

·         Updated crosswalk

o   No significant changes

 

·         New Complaint File

o   Brown Mackie San Antonia (fc # 21041443)

§  Old = 37 complaints

§  New = 38 complaints

 

·         Section 702

o   All schools should be listed as compliant

 

·         Caution Flags (Heightened Cash Monitoring)

o   NORTHWEST CAREER COLLEGE (fc # 24930828)

§  No more caution flag
[Comparison Tool Data Full 20160511.xlsx](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/files/259817/Comparison.Tool.Data.Full.20160511.xlsx)

**Comment by plusjeff** [comment]
@rickleegit I have this on my radar. Will chat with @ayaleloehr about walking through a data deploy.
