### ISSUE TITLE
A question: GIBCT title

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/gi-bill-comparison-tool#368]
People who don't know the brand don't understand the title. "Am I comparing GI Bills?" - they wouldn't expect the tool to be for comparing schools and benefits. We are looking at labels, and also trying to use it in more action oriented links. For example: "Compare schools that interest you using the GI Bill Benefits Comparison Tool"
- any issues to be aware of before rolling out this content change? 
- Is it possible to consider renaming the tool?

cc: @emilyville @staceylanger

**Comment by rickleegit** [comment]
This topic has been something that we have brought up in the past as well and we advocated for changing the name and rebranding. The EDU team was open to changing it but was very concerned about maintaining the brand equity that they have established. The issue with changing it now became the vets.gov comms blackout. They had asked to hold off on the change until we could assist in rebuilding establishing the brand through vets.gov comms such as launch announcements, etc. 

If we change it unilaterally, which we may choose to do, we just need to be prepared that there will be significant pushback. This tool and EDU are under the microscope of the GAO and the Hill, so they are very sensitive to this type of messaging change. If we are going to do this at the vets.gov level, my suggestion would be to prepare an air-tight business case (a one sheet, not a full-blown report) for the change and work through the EDU team before executing. An alternate and quicker resolution would be to ask Marina to talk to Coy about it and have him push it down. 

cc: @emilyville @staceylanger

**Comment by saintsoup52** [comment]
We have spent the past 2 1/2 years branding the GI Bill Comparison tool... that was no easy feat and changing the name of the tool would require us to do all that work again.

Additionally, the completed tool will allow a user to compare GI Bill benefits ("Chapter Chooser") and schools.

There is a long history why this was not called a GI Bill benefits calculator... while I didn't agree with that logic at the time, I think changing the name now would cause more confusion then it would resolve.

**Comment by maryannbrody** [comment]
Helpful to have all of this context. I think a good middle ground would be to use more actionable and descriptive language in links and buttons. (We are working to make links and labels more actionable globally across the site). 

For example: 

**<link>Compare estimated benefits by school<link>** 
Use the GI Bill Comparison Tool to compare GI Bill benefits at schools that interest you.

This isn't a change to the tool (can keep the name the same) -- just a global content change across the site. 

Thanks for the background!!

**Comment by rickleegit** [comment]
Agreed. Going to close this issue on the CT board.
