### ISSUE TITLE
Deploy 06/02/2016

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#374]
This deployment is BOTH data and code. Data file attached. GH won't take a csv, so I am attaching the original .xlsx file. It needs to be opened in Excel and saved as "data.csv". Then the magic can occur. 

The data set can be validate by:

1. Search for Ashford University
2. Ashford University page should render a caution flag. 

[Comparison Tool Data Full 20160601b.xlsx](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/files/296419/Comparison.Tool.Data.Full.20160601b.xlsx)

The code needs to reflect the addition of a caution flag link. The image below can be accessed by:

1. Search for argosy
2. Select an argosy from search results displaying a caution flag
3. Click on the info icon represented by a circle with a lower case 'i'.

The last caution flag should read:
_Iowa SAA approval ends 6/30/16 (Potential lapse in program approval and payment of GI Bill benefits.)_

Should be this:
<img width="1233" alt="screen shot 2016-06-02 at 3 58 05 pm" src="https://cloud.githubusercontent.com/assets/11138830/15759252/0883c422-28dc-11e6-823c-76811148a0c9.png">

cc: @saintsoup52, @SteffieP

**Comment by rickleegit** [comment]
@ayaleloehr: This was merged. Should be good to go for data and code.

**Comment by ayaleloehr** [comment]
@rickleegit please close once you check that everything looks good.

**Comment by rickleegit** [comment]
Validated as correct. Thanks!
