### ISSUE TITLE
Changing Message from Sec Bob on Footer

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/gi-bill-comparison-tool#378]
add <a href="/2015/11/11/why-we-are-designing-in-beta.html/">Message from the Secretary</a> under Creating Vets.gov and remove ghost button to be consistent with footer changes on vets-website repo.

**Comment by webinista** [comment]
This change was rolled into [va_common 0.4.1](https://rubygems.org/gems/va_common). It doesn't look like it's been deployed to vets.gov yet, however it _has_ been merged into `master` in the GIBCT repo.

**Comment by ayaleloehr** [comment]
Will be deployed Thursday.
