### ISSUE TITLE
GIBCT gitignore

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/gi-bill-comparison-tool#379]
I tried making footer changes in GIBCT page where the `Message from the Secretary` is now a link under Creating Vets.gov and the "A Message from Sec..." ghost button is removed. Looks like vendor/bundle (which is where I’m trying to make the changes) is in `.gitignore` . Seems like you're making gem changes -- could you help me whenever you can? Related to #378

FYI this is low priority.

**Comment by webinista** [comment]
This change was rolled into [va_common 0.4.1](https://rubygems.org/gems/va_common). It doesn't look like it's been deployed to GIBCT yet, however it _has_ been merged into `master` in that repo.
