### ISSUE TITLE
Update Caution Flag for all Ashworth Colleges

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#382]
There are 2 Ashworth Colleges on Comparison Tool that needs a Caution Flag. We would like to use the following existing caution flag:
Federal Trade Commission Filed Suit for Deceptive Advertising

	Ashworth College - facility code 21917411
	Ashworth College - facility code 25917411

We know this is short notice and would like this to be deployed June 30th.

**Comment by joduinn** [comment]
Found in triage.

Saw a bunch of other work in terms of updating GIBCT this week - @rickleegit @mphprogrammer has this already been resolved? 

cc @ayaleloehr @koconnor719 @staceylanger for context

**Comment by mphprogrammer** [comment]
Yes.

**Comment by joduinn** [comment]
Great, thanks @mphprogrammer

**Comment by mphprogrammer** [comment]
There are other issues that need to be fixed in the Data Service before the caution flags are updated.
