### ISSUE TITLE
Amend existing Caution Flag Tool Tip

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#384]
EDU would like to amend a current caution flag Tool Tip. We like to change the following:

Iowa SAA approval ends 6/30/16 (Potential lapse in program approval and payment of GI Bill benefits.)

New message should say the following:

Iowa SAA approval ends 9/18/16 (Potential lapse in program approval and payment of GI Bill benefits.)

EDU would like to have this change by the next maintenance update on Thursday, July 21, 2016.

**Comment by rickleegit** [comment]
@ericks24 Is there a reason that this can not be accomplished using the data service? I think our hope was that this type of change would be a self-service operation.

**Comment by ericks24** [comment]
I was unaware that we can use the data service to update Tool Tips.

**Comment by rickleegit** [comment]
Fair point. My bad...

**Comment by ayaleloehr** [comment]
Waiting on deploy now...

**Comment by ericks24** [comment]
Will this update deploy next Thursday

**Comment by ayaleloehr** [comment]
Hopefully on Monday as I have to deploy a couple other things then as well.

**Comment by ayaleloehr** [comment]
deployed.
