### ISSUE TITLE
New Caution Flag Tool Tip

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#386]
EDU added the following new Caution Flag to Comparison Tool:

Accreditor under review

We would like to add this new flag to the pop up Tool Tip for Caution Flags. The following link will be used when someone clicks on "Accreditor under review":

http://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#ACICS

EDU would this change to be included in the maintenance update on Thursday, July 21, 2016.

**Comment by ericks24** [comment]
Notice this new Caution Flag "Accreditor under review"  was not added to the Tool Tips on todays deployment.. Also I provided the hyper link being used for this Caution Flag.

**Comment by ayaleloehr** [comment]
It's there for me. You might have to try refreshing the page or clearing your cache if you just loaded the page recently before today.  Screenshot below of production:

<img width="1087" alt="screen shot 2016-07-21 at 8 06 58 pm" src="https://cloud.githubusercontent.com/assets/4719765/17042791/c56ead7c-4f7e-11e6-881a-e94386f2f417.png">
