### ISSUE TITLE
Reopen Issue #386

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gi-bill-comparison-tool#388]
I noticed the below information was not part of the deployment for Thursday, July 21, 2016.

EDU added the following new Caution Flag to Comparison Tool:

Accreditor under review

We would like to add this new flag to the pop up Tool Tip for Caution Flags. The following link will be used when someone clicks on "Accreditor under review":

http://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#ACICS

EDU would this change to be included in the maintenance update on Thursday, July 21, 2016.

**Comment by ayaleloehr** [comment]
It's there for me. You might have to try refreshing the page or clearing your cache if you just loaded the page recently before today. Screenshot below of production:

<img width="1087" alt="screen shot 2016-07-21 at 8 06 58 pm" src="https://cloud.githubusercontent.com/assets/4719765/17042812/0373a758-4f7f-11e6-95f5-80bd9d0dc25b.png">

@ericks24 please close if clearing your cache works. If it doesn't please leave another comment here as well.
