### ISSUE TITLE
Update GI Bill CT Constants

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gi-bill-comparison-tool#389]
On August 1st many of the GI Bill rates change... We need to update those rates and then push them live on the 1st.

**Comment by koconnor719** [comment]
is this a data update on your end patrick?   @mphprogrammer

**Comment by mphprogrammer** [comment]
Patrick has issued a pull request: Updated Post-9/11 GI Bill Rates #390 - I'll take a look at it.

**Comment by koconnor719** [comment]
Thx



Sent with Good (www.good.com)


-----Original Message-----

**Comment by saintsoup52** [comment]
This is not a data request but rather a change to java script that affects the constants that run the GI Bill calculator

**Comment by mphprogrammer** [comment]
@saneshark Should we close this ...

**Comment by saneshark** [comment]
Yes. Calculator constants have been updated manually. 

In the future we will begin discover and look to implement a mechanism for admins to be able to modify these if they wish and a notification will be sent to all parties that the constants have changed.

**Comment by saintsoup52** [comment]
Will the constants be in two places (like it is now) or one place (preferable)?

**Comment by saneshark** [comment]
@mphprogrammer can speak to that, but I was thinking it would live in one place (the database) and when the gids is initialized we load it into a singleton. Perhaps we have a concept like super admin. And super admin can update the constants which will update the DB and update the inmemory singleton holding the constants data. 

I am not sure we would need to version this per se but something to think about in a separate github issue we have for tracking that. I'm AFK but I will tag the issue so we can have further conversation around this there.

**Comment by mphprogrammer** [comment]
It should live in GIDS, IMHO. However, looking at GIDS code - Ben had created a CalculatorConstant model/table already loaded during seeds. At the present time there are no controller or views to edit them, however there is an endpoint to retrieve them. In addition, Ben had assigned, but not yet implemented versioning for the constants - although we'd need a separate versioning system for constants and data should we implement...
