### ISSUE TITLE
Add optional basic auth for GIBCT preview deployment

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gi-bill-comparison-tool#401]
To align with devops best practices in govcloud, we are going to configure a "preview" instance of GIBCT in production instead of using the staging environment for previewing data. This instance is not for public consumption so should be password-protected. 

I think it's sufficient to have a single username/password protecting the preview instance since the data is read-only. Basic auth needs to be toggle-able during deployment, so something like this in 
application_controller.rb:
`if ENV['GIBCT_BASIC_AUTH_ENABLED'] == "true"
  http_basic_authenticate_with name: ENV['GIBCT_BASIC_AUTH_USER'], password: ENV['GIBCT_BASIC_AUTH_PASSWORD']
`

Then deployment scripts can optionally pass this environment to the preview instance but not the public instance.

**Comment by jkassemi** [comment]
Are there any downsides to managing this authentication with the reverse proxy?

**Comment by patrickvinograd** [comment]
No, I suppose not. I will add a separate htpasswd file for the preview endpoint, and templateize it out of credstash instead of checked in. 

Will close this and wrap it into the existing gibct ticket(s).
