### ISSUE TITLE
500 server error due to get institutions profile with no facility code

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gi-bill-comparison-tool#406]
Production GIBCT has several 500 Internal Server Errors in the logs with flows like this:
```
I, [2016-09-07T19:17:47.996471 #2397]  INFO -- : Started GET "/gi-bill-comparison-tool/institutions/profile" for 152.131.36.97 at 2016-09-07 19:17:47 -0400
I, [2016-09-07T19:17:48.003722 #2397]  INFO -- : Processing by InstitutionsController#profile as */*
D, [2016-09-07T19:17:48.005282 #2397] DEBUG -- :   ESC[1mESC[36mInstitution Load
 (0.9ms)ESC[0m  ESC[1mSELECT  "institutions".* FROM "institutions" WHERE "institutions"."facility_code" IS NULL LIMIT 1ESC[0m
I, [2016-09-07T19:17:48.016436 #2397]  INFO -- : Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.9ms)
F, [2016-09-07T19:17:48.016973 #2397] FATAL -- :
NoMethodError (undefined method `get_veteran_retention_rate' for nil:NilClass):  app/controllers/institutions_controller.rb:26:in `profile'
```

1. institutions_controller.rb does not have an adequate guard against Institution.find_by not returning anything, and then tries to call get_veteran_retention_rate on a nil
2. Not sure how /institutions/profile is being called with no facility code parameter, whether that's an error in autocomplete or something else.

**Comment by patrickvinograd** [comment]
Most of the instances of this look like somebody editing a URL from a previouis query and omitting the facility_code parameter, e.g. entering "gi-bill-comparison-tool/institutions/profile" with no query params at all. There are a few that do include a facility_code and for which when I retry the logged query params, I get a successful result in dev, but not in prod or staging. Perhaps those institutions were removed from the tool and bookmarked results are now returning errors. 

In any case I don't think there's any big logic error, just need to guard against a nil find_by and return a suitable error result like a 404.

**Comment by patrickvinograd** [comment]
@ayaleloehr What would you like the behavior to be:

1) Return a 404 result (due to no facility_code, or unknown facility_code). There's no 404 template for this app so it would be a bare page with an error message like "Institution Not Found"
2) Generate a templated profile page with no school data, just a link back to the front page of the app (similar to what happens when you search for a term that returns no results).
3) Generate a templated custom 404 error page that kicks back to the front page. 

1 is more REST-fully correct, 2 is nicer user experience in context of the rest of the app. 3 is both correct and nice but would take the most time with my scanty knowledge of rails views.

**Comment by patrickvinograd** [comment]
WIP messing with both approaches here: https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/tree/patrick-no-facility-code-error

**Comment by ayaleloehr** [comment]
Let's go with #2.  I agree that idiomatically we should return a 404, but given that we don't have a template here, I don't think it's worth the time right now to create one. Option 2 (basically a blank profile) feels like a good compromise to tell the user what the problem was and give them an option to do a new search.  

@patrickvinograd can you please include a screenshot of what this looks like in the PR when you open it?
