### ISSUE TITLE
Incorrect GI Bill Rates on CT

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gi-bill-comparison-tool#411]
Currently the GI Bill Comparison Tool is showing two different rates for the tuition/fees cap and living allowance rates for foreign schools and distance schools. 

We need to fix this ASAP!

![image](https://cloud.githubusercontent.com/assets/4397508/18563822/1b3bccc2-7b57-11e6-9701-7f3a5f1a52eb.png)

![image](https://cloud.githubusercontent.com/assets/4397508/18563844/2c12a17e-7b57-11e6-9d3b-9842c6212ac6.png)

I will submit a pull request in the short term, but we also need to address the longer term problem as well.

This is happening because "constants" that run the benefit estimator and the calculator now appear in two separate places in the code (see below). When we updated the rates, we only did it in one place but not the other.

The original intent was to have the constants in one place so that they could be easily updated when the new rates would take affect and those "constants" would then feed the rest of the tool. There are 18 different constants and having them in two places will likely make errors like this happen again.

**ESTIMATOR Code**
![image](https://cloud.githubusercontent.com/assets/4397508/18563658/7d7f5d14-7b56-11e6-98c1-45d443ca96cc.png)

https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/blob/216525ccf23ad60b1f65f3acafa40bbfa2db757e/app/assets/js/estimator.js

**CALCULATOR Code**
![image](https://cloud.githubusercontent.com/assets/4397508/18563975/a22eda44-7b57-11e6-8eab-30bfdfb7fb8f.png)

https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/blob/942839e67cc84e5ae576636f1d004081f0877c73/app/assets/js/calculator.js

**Comment by patrickvinograd** [comment]
#412 is deployed to production in #414, and per guidance from @ayaleloehr it appears that the constants are now correct.
