### ISSUE TITLE
Limit size of results from search and autocomplete.

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gi-bill-comparison-tool#435]
It appears that searching for a generic term like "A" will potentially return the entire ResultSet for matching institutions, including the entire institution object. This exerts memory pressure on the GIBCT instance. Some of the fetches were turned to `SELECT COUNT(*)` in an earlier PR, but there is still one full SELECT:
```
Started GET "/gi-bill-comparison-tool/institutions/search?utf8=%E2%9C%93&source=home&military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&institution_search=A"
...
Institution Load (962.1ms)ESC[0m  SELECT institutions.*, institution_types.name FROM "institutions" INNER JOIN "institution_types" ON "institution_types"."id" = "institutions"."institution_type_id" WHERE (lower(facility_code) = ('a') OR lower(institution) LIKE ('%a%') OR lower(city) LIKE ('%a%'))  ORDER BY "institutions"."institution" ASC
```

The auto-complete mechanism is similarly unlimited - the memory pressure may not be as much of an issue since it's only selecting the insitution name and code, but as a user starts typing "uni"..."univer"..."university"..."university of", it is resulting in lots of database queries with large result sets that the user is never going to page through to find their institution. We can easily limit this to 10-20 results.

**Comment by patrickvinograd** [comment]
Would like to prioritize this as it is resulting in some instance memory alerts in production.

**Comment by patrickvinograd** [comment]
Part of the reason GIBCT does a full table scan is so it can populate the item counts for the various filter/query refinement options that are presented in the results page. Another option for reducing the cost of many-result searches is to impose a minimum search term length - searching for a vowel like "A" or "E" returns ~32k results. Searching for common digraphs or trigraphs like "th" or "uni" return ~5k results.

**Comment by saintsoup52** [comment]
The old results would only appear after the first three letters were typed

**Comment by patrickvinograd** [comment]
@saintsoup52 Yes, sorry I was not clear - the autocompletion waits for 3 letters, but you can submit a search for a single letter and that is what is loading a huge result set.
