### ISSUE TITLE
Isolate GIBCT database from rest of vets-api

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gi-bill-comparison-tool#438]
Current plan is to integrate the GIBCT API with vets-api and make the GIBCT frontend a part of vets-website.

When doing so, we should implement it such that GIBCT continues to read from a separate database than vets-api. While this introduces some rails implementation and devops overhead, it is needed in order to isolate GIDS's security and database-access domain from the rest of vets-api. Because the GIDS application has stakeholder logins and because of the way it does a mass push of data to the GIBCT database, it should not have a connection to the same database as vets-api as a whole. It's also a latency concern during the mass-update of GIBCT records from GIDS.

**Comment by saintsoup52** [comment]
Random question about this... will the GI Bill CT data be available to the public through this vets.gov API?

That would be awesome.

**Comment by ayaleloehr** [comment]
I don't think this initial issue is relevant anymore. 

To @saintsoup52 's question, I believe yes the GI Bill data should be available through the vets.gov API once these changes are complete. @saneshark @mphprogrammer or @ben-USDS-damman please reopen and comment if that's incorrect.
