### ISSUE TITLE
Undefined method empty? for nil

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/gi-bill-comparison-tool#439]
Seeing a few requests submitted by bots without a valid institution search term that lead to the following server error:

```
Processing by InstitutionsController#search as HTML
NoMethodError (undefined method `empty?' for nil:NilClass):
app/models/institution.rb:133:in `search'
app/controllers/institutions_controller.rb:47:in `search'
```

This should be using a `blank?` check instead to prevent the bad input from throwing an error.

**Comment by patrickvinograd** [comment]
Fixed via #443.
