### ISSUE TITLE
No Exit Icon?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/gi-bill-comparison-tool#444]
Looking through GIBCT I'm seeing a bunch of this error:

`ActionController::RoutingError (No route matches [GET] "/images/icons/exit-icon.png"):`

Not the highest priority probably, but would be nice to fix if easy.

**Comment by mphprogrammer** [comment]
@ayaleloehr Could this be related to the va-common stuff? Was there an official exit-icon.png?

**Comment by ayaleloehr** [comment]
Oops, this is a duplicate of #408 going to close this, as that issue has more detail.
