### ISSUE TITLE
Is separate institution_type table needed?

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gi-bill-comparison-tool#445]
Hoping this can be decided/addressed in the context of port to vets-api if it has not been already.  Why is there a separate institution_types table with only a single column "name" (plus the created_at/updated_at metadata columns). If there's no other data associated with an institution type then there's no schema normalization benefit to be had with a separate table versus just having an institution_type column in the institutions table.

As it is we incur the cost of doing a useless join between these tables on several of the queries.

**Comment by mphprogrammer** [comment]
It is not necessary, and can be moved into the institutions table. It was an artifact of when the plans for the GIBCT were more ambitious, but shelved due to the quick initial turn around required. @typesend can remove during the port.

**Comment by saintsoup52** [comment]
I think this was used as part of the filtering process in the old search function. FWIW

**Comment by typesend** [comment]
Removing it
