### ISSUE TITLE
Urgent: Backend of the CT, P911TF not ingesting data

### ISSUE THREAD

**Issue by NobleDon** [department-of-veterans-affairs/gi-bill-comparison-tool#474]
We are having a problem with the Comparison Tool ingesting the P911TF file . I have tried several  times to upload the file and received the message below. This information is very vital to data credibility, the file has been saved in the correct format we need a resolution to this expedited for we can continue to push valid data.

[Urgent CT problem.docx](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/files/1001477/Urgent.CT.problem.docx)

**Comment by mphprogrammer** [comment]
@NobleDon please send me the file you are trying to upload

**Comment by saintsoup52** [comment]
I diagnosed the issue... sorry for the fire alarm. The column header names had changed.

In general it would helpful if the warning just said missing column headers with the names.

**Comment by mphprogrammer** [comment]
@saintsoup52 is it working now?

**Comment by saintsoup52** [comment]
Yes... I fixed the data file to match the column names.

**Comment by mphprogrammer** [comment]
Marking this as closed per Patrick's response.

**Comment by jmcneal65** [comment]
Thanks Marc.

With best personal regards,

       John

John T. McNeal
U.S. Department of Veterans Affairs
Veterans Benefits Administration, Office of Education Service
Business Process Development – Legacy Systems (224B)
Office: 202.461.9613 | iPhone: 202-957-2281





Confidentiality Notice: If you received this email by mistake, you should notify the sender of the mistake and delete the email and any attachments. An inadvertent disclosure is not intended to waive any privileges.

**Comment by NobleDon** [comment]
Thanks for looking into it…
